name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2.1.5
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install 🔧
        run: |
          yarn

      - name: Test 🧪
        run: |
          yarn test --coverage=true

      - name: Coveralls 🙈
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
