name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install 🔧
        run: |
          yarn

      - name: Test 🧪
        run: |
          yarn test
